#!/usr/bin/env python3
"""Per-model thinking mix from the published λ-bench labels -> blog data.

    python probe/build_thinking_mix.py [path-to-agent-capability-threshold]

WHY THIS DATA IS NOT IN THIS REPO

It belongs to `agent-capability-threshold`, which is public, so the blog cites
the file rather than vendoring a copy that could drift from the post it came
from. This script records the source commit so a number in the chart can be
traced to the exact bytes it was computed from.

    https://github.com/adam-s/agent-capability-threshold
    web/src/lib/data/annotated-traces.ts

WHAT IT IS

Eight traces from Claude Haiku, Opus and Sonnet on long multiplication and
modular exponentiation, 903 segments, labelled with the nine categories that
reasoning-grid's v1 scheme was later adapted from.

CATEGORIES, NOT OODA PHASES, AND THAT IS DELIBERATE

The obvious chart is share-of-thinking per OODA phase. It cannot be drawn
honestly from this scheme. `.agents/reference/flame-rubric-reasoning-grid.md` maps
`STRATEGY` (this scheme's `DECOMPOSITION`) to BOTH Orient and Decide, because
in these traces the model states a plan and commits in one breath. A phase
chart would have to double-count the largest category or put it somewhere by
fiat. Since `DECOMPOSITION` is 13.6% overall and 31.2% of Sonnet, that choice
would carry the whole result.

A mapping that is not a function is the defect the v2 rebuild was done to
remove. So the chart shows the categories as labelled and says so.

WHAT IT SHOWS

The nine categories describe all three models. The proportions do not agree:
`DECOMPOSITION` runs from 3.8% of Haiku's thinking to 31.2% of Sonnet's. That
is a cross-model result about how models reason, which the reliability grid in
this repo does not have.
"""
import collections
import json
import os
import re
import subprocess
import sys

DEFAULT_SRC = os.path.expanduser("~/Projects/agent-capability-threshold")
REL = "web/src/lib/data/annotated-traces.ts"
REPO = "https://github.com/adam-s/agent-capability-threshold"
OUT = "blog/src/lib/data/thinking-mix.ts"

# Fixed display order: roughly the order a trace moves through them, so the
# bars are comparable left to right instead of re-sorting per model.
ORDER = [
    "TASK_SETUP",
    "DECOMPOSITION",
    "PROCEDURAL_TRACKING",
    "ARITHMETIC",
    "EXECUTION",
    "VERIFICATION",
    "ERROR_CORRECTION",
    "SURRENDER_DELIBERATION",
    "SURRENDER",
]

HEADER = '''/**
 * GENERATED by probe/build_thinking_mix.py -- do not edit.
 *
 * Per-model share of labelled thinking segments, from the PUBLISHED labels in
 * agent-capability-threshold. The data is not copied into this repo; `source`
 * below carries the commit and the URL so any number here can be traced to the
 * bytes it came from.
 *
 * CATEGORIES, NOT OODA PHASES. The v1 rubric maps `STRATEGY` (this scheme's
 * `DECOMPOSITION`) to both Orient and Decide, so a phase chart would have to
 * double-count the largest category. See the build script for the full
 * argument.
 */
export type MixModel = {
  readonly model: string;
  readonly traces: number;
  readonly segments: number;
  /** category -> segment count */
  readonly counts: Readonly<Record<string, number>>;
};

export type ThinkingMix = {
  readonly order: readonly string[];
  readonly labels: Readonly<Record<string, string>>;
  readonly models: readonly MixModel[];
  readonly segments: number;
  readonly source: {
    readonly repo: string;
    readonly path: string;
    readonly commit: string;
    readonly url: string;
  };
};

export const THINKING_MIX: ThinkingMix = '''

LABELS = {
    "TASK_SETUP": "Setup",
    "DECOMPOSITION": "Decomposition",
    "PROCEDURAL_TRACKING": "State tracking",
    "ARITHMETIC": "Arithmetic",
    "EXECUTION": "Connective",
    "VERIFICATION": "Verification",
    "ERROR_CORRECTION": "Error correction",
    "SURRENDER_DELIBERATION": "Deciding to quit",
    "SURRENDER": "Quitting",
}


def load(path):
    """Pull the ANNOTATED_TRACES array out of the TypeScript module."""
    s = open(path).read()
    i = s.index("ANNOTATED_TRACES")
    j = s.index("[", i)
    depth = 0
    for k in range(j, len(s)):
        if s[k] == "[":
            depth += 1
        elif s[k] == "]":
            depth -= 1
            if depth == 0:
                break
    return json.loads(s[j:k + 1])


def main(src=DEFAULT_SRC):
    path = os.path.join(src, REL)
    if not os.path.exists(path):
        sys.exit(f"not found: {path}\nPass the path to agent-capability-threshold.")

    commit = subprocess.run(
        ["git", "-C", src, "rev-parse", "HEAD"],
        capture_output=True, text=True,
    ).stdout.strip() or "unknown"

    traces = load(path)
    by = collections.defaultdict(collections.Counter)
    n_traces = collections.Counter()
    for t in traces:
        n_traces[t["model"]] += 1
        for r in t["rows"]:
            by[t["model"]][r["category"]] += 1

    models = []
    for m in sorted(by, key=lambda m: -sum(by[m].values())):
        c = by[m]
        models.append({
            "model": m,
            "traces": n_traces[m],
            "segments": sum(c.values()),
            "counts": {k: c[k] for k in ORDER if c[k]},
        })

    used = [k for k in ORDER if any(k in m["counts"] for m in models)]
    data = {
        "order": used,
        "labels": {k: LABELS[k] for k in used},
        "models": models,
        "segments": sum(m["segments"] for m in models),
        "source": {
            "repo": REPO,
            "path": REL,
            "commit": commit,
            "url": f"{REPO}/blob/{commit}/{REL}",
        },
    }

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, OUT)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(HEADER + json.dumps(data, indent=1) + ";\n")

    print(f"wrote {OUT}  ({os.path.getsize(out)/1024:.1f} KB)")
    print(f"  source {commit[:12]}  {len(traces)} traces, {data['segments']} segments")
    for m in models:
        s = m["segments"]
        d = m["counts"].get("DECOMPOSITION", 0)
        e = m["counts"].get("ERROR_CORRECTION", 0)
        print(f"  {m['model']:7s} {m['traces']} traces  {s:4d} segments  "
              f"decomposition {d/s*100:4.1f}%  error correction {e/s*100:4.1f}%")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC)
