#!/usr/bin/env python3
"""Thinking text + the arithmetic it states -> blog/src/lib/data/opener.ts

    python probe/build_opener.py

The opening figure runs a model's thinking past the reader and lands each
arithmetic claim in a second pane as it is stated, already checked. So this
script has to do two things: ship the raw thinking, and extract every closed
arithmetic claim in it with a verdict computed rather than trusted.

## What counts as a claim

A model writes two kinds of `=` line. One states a result. The other REWRITES
the same quantity -- "A x 50,000,000 = A x 5 x 10^7" -- which is not a claim
that can be true or false. Only the first is extracted, so a rewriting is never
reported as an error.

Three passes of this were wrong before it was right, all in the same direction:
inventing errors in runs that made none.

  1. A loose right-hand side read "A x 50,000,000 = A x 5 x 10^7" as a claim
     that the product is 2,053,896, and "= 80.4 x 10^6" as a claim it is 80.
  2. Guarding with a lookahead let the regex BACKTRACK into a shorter number
     when the guard failed, so "= 18,000,000" matched as "= 1" and trace A --
     which states 67 facts and gets every one right -- appeared to make
     seventeen errors.
  3. Rejecting a following "." killed sentence-ending periods along with
     decimals, and dropped the one real error there is.

The fix for all three is to match MAXIMAL runs of digits and commas, so there is
no shorter prefix to fall back into, then check the neighbourhood separately.
A number is also required to be well formed -- comma groups of exactly three --
which rejects the model interrupting itself mid-number, as trace C does at
"= 31,675,554,0 (wait, need to do this properly)".

## Result

  trace A, converged right   72 claims, 0 false
  trace B, converged wrong   36 claims, 1 false -- an ADDITION; every one of
                             its multiplications is correct
  trace C, never answered    52 claims, 0 false -- it does not fail at
                             arithmetic, it fails to commit

Subtraction was added after an adversarial pass asked what the extractor cannot
see. It could only see x and +, so eleven subtraction claims went ungraded and
"160 claims, 1 false" was really "160 multiplications and additions". All eleven
turned out correct, so the headline did not move -- but it was not defensible
until they were checked.

Those counts are printed on every run. If they move, the extractor changed and
the prose that quotes them needs re-checking.
"""
import argparse
import glob
import json
import os
import re
import sys

OUT = "blog/src/lib/data/opener.ts"
MODEL = "Qwen3-4B"

# Subtraction is checked; DIVISION deliberately is not. A model casting out
# nines writes "87 / 9 = 9", meaning nine remainder six, and grading that as
# false would report a correct check as an error. Subtraction has no such
# second reading.
EQ = re.compile(r"([\d,]+)\s*(×|x|\*|\+|-|−)\s*([\d,]+)\s*=\s*([\d,]+)")


def wellformed(s):
    """A number the model finished writing. Comma groups are exactly three."""
    if s.startswith(",") or s.endswith(","):
        return False
    p = s.split(",")
    return len(p) == 1 or (1 <= len(p[0]) <= 3 and all(len(g) == 3 for g in p[1:]))


def claims(t):
    """Every closed arithmetic claim in `t`, with the truth computed."""
    out = []
    for m in EQ.finditer(t):
        x, op, y, z = m.group(1), m.group(2), m.group(3), m.group(4)
        if not all(map(wellformed, (x, y, z))):
            continue
        if re.search(r"[-+×x*/^]\s*$", t[max(0, m.start() - 2):m.start()]):
            continue                                   # third term of a longer sum
        if op in "-−" and re.search(r"\d\s*$", t[max(0, m.start() - 2):m.start()]):
            continue                                   # a minus sign inside a range
        if re.match(r"[.,]\d|\s*[-+×x*/^]", t[m.end():m.end() + 2]):
            continue                                   # a decimal, or a rewriting
        a, b, c = (int(v.replace(",", "")) for v in (x, y, z))
        if not a or not b:
            continue
        sym = {"+": "+", "-": "−", "−": "−"}.get(op, "×")
        truth = a + b if sym == "+" else a - b if sym == "−" else a * b
        out.append({"at": m.start(), "end": m.end(), "op": sym,
                    "a": str(a), "b": str(b), "said": str(c),
                    "truth": str(truth), "ok": truth == c})
    return out


def load(uid, runs):
    for f in sorted(glob.glob(os.path.join(runs, "*.jsonl"))):
        for line in open(f):
            if uid not in line:
                continue
            j = json.loads(line)
            if not (j.get("model") or "").endswith(MODEL):
                continue
            raw = j.get("raw_text") or ""
            if "</think>" not in raw:
                continue
            return j, raw[:raw.index("</think>")].replace("<think>", "", 1).strip()
    return None, None


HEADER = '''/**
 * GENERATED by probe/build_opener.py -- do not edit.
 *
 * A model's thinking, and every arithmetic claim inside it with the answer
 * computed rather than taken on trust. `at` is a character offset into
 * `thinking`, so the figure can land a claim in the second pane exactly when
 * the stream reaches it.
 *
 * `segments` are the same boundaries and categories the flame figure uses, so
 * the stream can be tinted by what kind of move the model was making.
 */
export type Claim = {
  readonly at: number;
  readonly end: number;
  readonly op: '×' | '+' | '−';
  /** decimal strings: several exceed Number.MAX_SAFE_INTEGER */
  readonly a: string;
  readonly b: string;
  readonly said: string;
  readonly truth: string;
  readonly ok: boolean;
};

export type OpenerSegment = {
  readonly start: number;
  readonly end: number;
  readonly category: string;
  readonly label: string;
};

export type OpenerTrace = {
  readonly key: string;
  readonly cell: string;
  readonly x: string;
  readonly y: string;
  readonly truth: string;
  readonly answer: string | null;
  readonly outcome: string;
  readonly verdict: string;
  readonly thinking: string;
  readonly claims: readonly Claim[];
  readonly segments: readonly OpenerSegment[];
};

export const OPENER: readonly OpenerTrace[] = '''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("-o", "--out", default=OUT)
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ts = open(os.path.join(root, "blog/src/lib/data/carrychain-traces.ts")).read()
    built = json.loads(ts[ts.index("= [") + 2:ts.rindex("];") + 1])

    out = []
    for tr in built:
        j, think = load(tr["uid"], args.runs)
        if think is None:
            sys.exit(f"no {MODEL} thinking found for {tr['key']} ({tr['uid']})")
        cl = claims(think)
        # Segment offsets are into the trace as segmented, which starts at the
        # same place this thinking does; leaves carry the boundaries.
        # SORTED BY START. The flame rows are ordered for flame rendering, which
        # is not ascending by offset -- trace A jumps from 17,682 back to 952 at
        # index 19. Anything that walks these in array order and stops at the
        # first segment past a cursor renders a fifth of the trace, in the wrong
        # order, and looks fine because the pane still fills.
        segs = sorted(
            ({"start": r["start"], "end": r["start"] + r["width"],
              "category": r["category"], "label": r["label"]}
             for r in tr["rows"] if not r.get("container")),
            key=lambda s: s["start"])
        # The segments must tile the thinking exactly, or the left pane is not
        # showing what the model wrote. Checked here rather than trusted.
        rebuilt = "".join(think[s["start"]:min(s["end"], len(think))] for s in segs)
        if rebuilt != think:
            sys.exit(f"{tr['key']}: segments do not tile the thinking "
                     f"({len(rebuilt):,} chars rebuilt vs {len(think):,})")
        out.append({"key": tr["key"], "cell": tr["cell"], "x": tr["x"], "y": tr["y"],
                    "truth": tr["truth"], "answer": tr["answer"],
                    "outcome": tr["outcome"], "verdict": tr["verdict"],
                    "thinking": think, "claims": cl, "segments": segs})
        bad = [c for c in cl if not c["ok"]]
        print(f"  trace {tr['key']} {tr['cell']:>5}  {tr['outcome']:16s} "
              f"{len(think):6,} chars  {len(cl):3d} claims, {len(bad)} false")
        for c in bad:
            print(f"      {int(c['a']):,} {c['op']} {int(c['b']):,} = {int(c['said']):,}"
                  f"   actually {int(c['truth']):,}")

    path = args.out if os.path.isabs(args.out) else os.path.join(root, args.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(HEADER + json.dumps(out, indent=1, ensure_ascii=False) + ";\n")
    tot = sum(len(t["claims"]) for t in out)
    wrong = sum(1 for t in out for c in t["claims"] if not c["ok"])
    print(f"\nwrote {args.out}  ({os.path.getsize(path)/1024:.0f} KB)")
    print(f"  {tot} claims across {len(out)} traces, {wrong} false")


if __name__ == "__main__":
    main()
