"""Emit the allocation figure's data by READING THE DECISION, not remaking it.

docs/runs-per-cell.md holds two committed 14x14 tables: how many runs each cell
earns under cost-weighted Neyman allocation, and the predicted pass rate that
produced them. Those tables are the decision. This script parses them and writes
the blog's data module, so the figure renders the decision instead of a second
opinion about it.

## Why parse rather than recompute

The first version of this file derived its own allocation from the sweep. That
was wrong twice over. It fed raw per-cell rates into `sqrt(p(1-p))` when cells
hold as few as three generations, so neighbours came out 3 and 24 with one
generation between them. And even once the rate was fitted, it produced numbers
near the committed ones but not equal to them, which is worse than either being
right or being absent. Two allocations in one repository is one too many.

Recomputing from the fit the doc records, `logit p = 11.012 - 2.649 log N` with
`tokens = 505 N^0.714`, lands close but not exact: 8x8 comes out 21 against the
committed 23, and 14x14 comes out 6 against 7. The scaling constant behind the
committed table is not written down. Parsing the table sidesteps that entirely
and has the better property anyway, which is that editing the doc moves the
figure.

Run: python3 probe/build_allocation.py
"""

from __future__ import annotations

import re

SRC = "docs/runs-per-cell.md"
OUT = "blog/src/lib/data/allocation.ts"

# The doc decides 14x14. The figure shows the top-left 12x12 of it, which is the
# grid the rest of the post is about, and the ridge has already turned and
# started falling well inside that corner. Cropping does not change a single
# allocated number, it only stops the figure claiming a wider grid than the page
# ever measured.
MAX_DIGITS = 12

RUNS_HEADING = "## 3. Runs per cell"
RATE_HEADING = "### Predicted pass rate that produced it"


def parse_matrix(text: str, heading: str) -> dict[tuple[int, int], int]:
    """Read the first markdown table after `heading` as a square matrix.

    Rows are labelled `**7**` and cells are bare integers. Anything that is not
    a data row is skipped, so the alignment row and the column header fall out
    without needing to be matched.
    """
    start = text.index(heading) + len(heading)
    # Stop at the next heading. Without this the slice runs into the following
    # section, reads its table too, and the second one silently overwrites the
    # first -- which is exactly how "runs" came back holding pass rates.
    nxt = re.search(r"^#{1,4} ", text[start:], flags=re.M)
    body = text[start : start + nxt.start()] if nxt else text[start:]
    out: dict[tuple[int, int], int] = {}
    for line in body.splitlines():
        m = re.match(r"^\|\s*\*\*(\d+)\*\*\s*\|(.+)\|\s*$", line)
        if not m:
            continue
        a = int(m.group(1))
        values = [v.strip() for v in m.group(2).split("|")]
        for i, v in enumerate(values, start=1):
            if re.fullmatch(r"\d+", v):
                out[(a, i)] = int(v)
    if not out:
        raise SystemExit(f"no table found under {heading!r} in {SRC}")
    return out


def main() -> None:
    text = open(SRC).read()
    runs = parse_matrix(text, RUNS_HEADING)
    rate = parse_matrix(text, RATE_HEADING)

    missing = set(runs) ^ set(rate)
    if missing:
        raise SystemExit(f"the two tables disagree on {len(missing)} cells: {sorted(missing)[:5]}")

    cells = sorted(
        k for k in (set(runs) & set(rate)) if k[0] <= MAX_DIGITS and k[1] <= MAX_DIGITS
    )

    max_a = max(a for a, _ in cells)
    max_b = max(b for _, b in cells)

    body = ",\n".join(
        "  { a: %d, b: %d, p: %s, runs: %d }" % (a, b, rate[(a, b)] / 100, runs[(a, b)])
        for (a, b) in cells
    )

    with open(OUT, "w") as fh:
        fh.write(
            "/**\n"
            " * GENERATED by probe/build_allocation.py from docs/runs-per-cell.md.\n"
            " * Do not edit. Change the doc and rerun.\n"
            " *\n"
            " *   p     predicted pass rate, from the fitted surface\n"
            " *   runs  cost-weighted Neyman allocation for that cell\n"
            " *\n"
            " * This is the DESIGN, not a record of the sweep. The sweep that ran\n"
            " * used 3, 6 or 12 per cell.\n"
            " */\n"
            "export type AllocCell = {\n"
            "  readonly a: number;\n"
            "  readonly b: number;\n"
            "  readonly p: number;\n"
            "  readonly runs: number;\n"
            "};\n\n"
            "export const ALLOC_MAX_A = %d;\n"
            "export const ALLOC_MAX_B = %d;\n\n"
            "export const ALLOCATION: readonly AllocCell[] = [\n%s,\n];\n"
            % (max_a, max_b, body)
        )

    lo, hi = min(runs.values()), max(runs.values())
    peak = max(cells, key=lambda k: runs[k])
    print(f"wrote {OUT}: {len(cells)} cells from {SRC}")
    print(f"  runs {lo} to {hi}, peak at {peak[0]}x{peak[1]}")
    for k in [(1, 1), (8, 8), (MAX_DIGITS, MAX_DIGITS)]:
        if k in runs:
            print(f"  {k[0]:>2}x{k[1]:<2} {runs[k]:>3} runs at {rate[k]}%")


if __name__ == "__main__":
    main()
