#!/usr/bin/env python3
"""Per-cell trial outcomes for the animated surface.

Emits one array of 1/0 per grid cell, in the order the trials were run, so the
browser can recompute the surface at any trial count instead of shipping 55
pre-rendered frames. That is what makes the scrubber honest: frame t is the
rate after exactly t trials, computed from the same outcomes every other chart
in this project scores from.

Condition filtering is identical to probe/render_animation.py, deliberately --
if these two disagree, one of them is lying about the same runs.

    python probe/build_surface.py
"""
import argparse
import collections
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from reduce_grid import load  # noqa: E402

OUT = "blog/src/lib/data/surface.ts"
# A cell whose generations ran against different context ceilings is only
# comparable while nothing came close to the smaller one.
SAFE = 0.80


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--model", default="Qwen/Qwen3-4B")
    ap.add_argument("-o", "--out", default=OUT)
    args = ap.parse_args()

    recs = []
    for f in sorted(glob.glob(os.path.join(args.runs, "*.jsonl"))):
        for r in load([f], model=args.model, temperature=0.7):
            if r.get("top_p") != 1.0 or r.get("thinking_observed") is not True:
                continue
            recs.append(r)

    by = collections.defaultdict(list)
    for r in recs:
        by[(r["a"], r["b"])].append(r)

    dropped = 0
    for k, rs in list(by.items()):
        ceils = {r.get("engine_max_len") for r in rs if r.get("engine_max_len")}
        if len(ceils) > 1:
            mn = min(ceils)
            if any(r["completion_tokens"] > SAFE * mn for r in rs):
                keep = [r for r in rs if r.get("engine_max_len") == max(ceils)]
                dropped += len(rs) - len(keep)
                by[k] = keep

    cells, dim, maxn, total = {}, 0, 0, 0
    for (a, b), rs in by.items():
        rs = sorted(rs, key=lambda r: (r["instance_id"], r.get("sweep_id", "")))
        cells[f"{a}x{b}"] = [1 if r["correct"] else 0 for r in rs]
        dim = max(dim, a, b)
        maxn = max(maxn, len(rs))
        total += len(rs)

    doc = {
        "model": args.model.split("/")[-1],
        "dim": dim,
        "maxTrials": maxn,
        "outcomes": total,
        "cells": dict(sorted(cells.items(), key=lambda kv: (len(kv[0]), kv[0]))),
    }

    ts = f"""/**
 * GENERATED by probe/build_surface.py -- do not edit.
 *
 * One array per grid cell, 1 = exactly correct, in the order the trials ran.
 * The surface at trial t is the running mean of the first t entries, so every
 * frame is computed in the browser rather than shipped. Cells differ in length
 * because the sweep spent more trials where the outcome was uncertain: a cell
 * that stops changing part-way through the scrub is one nobody was still
 * measuring, not one that converged.
 */
export type SurfaceData = {{
  readonly model: string;
  readonly dim: number;
  readonly maxTrials: number;
  readonly outcomes: number;
  /** "AxB" -> per-trial outcomes, in run order. */
  readonly cells: Readonly<Record<string, readonly number[]>>;
}};

export const SURFACE: SurfaceData = {json.dumps(doc, indent=1)};
"""
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(ts)

    lens = collections.Counter(len(v) for v in cells.values())
    print(f"wrote {args.out}  ({os.path.getsize(args.out) / 1024:.0f} KB)")
    print(f"  {len(cells)} cells, dim {dim}, {total:,} outcomes, up to {maxn} trials")
    print(f"  trials per cell: " + "  ".join(f"n={n}x{c}" for n, c in sorted(lens.items())))
    if dropped:
        print(f"  {dropped} records dropped for mixed context ceilings")


if __name__ == "__main__":
    main()
