"""Emit the running estimate for the two repeated-sampling runs.

One line per run: after each generation, what the rate would have read if you
had stopped there. Around it, the 95% interval at that sample size.

The pair is the argument. Both runs converge on a number they were always going
to converge on, and both spend their first few dozen generations somewhere else
entirely. The interval is what says how much of the early wandering is real.

Wilson rather than Wald, because Wald is nonsense at the sample sizes that make
this figure interesting. At n=1 with one hit, Wald gives [1.0, 1.0] -- zero
width, total confidence, from a single generation. Wilson gives [0.21, 1.0],
which is the honest answer and the one the figure needs at exactly the point a
reader is most likely to be fooled.

Downsampled for the page. Early generations are kept at full resolution because
that is where the line moves; later ones thin out because a path with six
thousand points is a megabyte of SVG that draws the same picture.

Run: python3 probe/build_convergence.py
"""

from __future__ import annotations

import glob
import json
import math

OUT = "blog/src/lib/data/convergence.ts"

RUNS = [
    {
        "key": "11x8",
        "glob": "runs/20-dist11x8*.jsonl",
        "label": "11 x 8",
        "note": "reasoning on",
    },
    {
        "key": "5x5",
        "glob": "runs/21-*5x5-nothink*.jsonl",
        "label": "5 x 5",
        "note": "reasoning off",
    },
]

# Every point up to here, then one in every `THIN` after. 120 covers the region
# where the estimate is still visibly moving.
DENSE_TO = 120
THIN = 12


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return 0.0, 1.0
    p = k / n
    d = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / d
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return max(0.0, centre - half), min(1.0, centre + half)


def main() -> None:
    out = []
    for spec in RUNS:
        rows: list[dict] = []
        for path in sorted({p for p in glob.glob(spec["glob"], recursive=True)}):
            with open(path) as fh:
                rows.extend(json.loads(line) for line in fh if line.strip())
        if not rows:
            raise SystemExit(f"no records for {spec['glob']}")
        # Instance order, so the walk is the order the problems were drawn in
        # rather than the order the GPU happened to finish them. Finish order
        # correlates with generation length, which correlates with difficulty.
        rows.sort(key=lambda r: r["instance_id"])

        pts = []
        k = 0
        for i, r in enumerate(rows, start=1):
            k += 1 if r.get("correct") else 0
            if i <= DENSE_TO or i % THIN == 0 or i == len(rows):
                lo, hi = wilson(k, i)
                pts.append([i, round(k / i, 4), round(lo, 4), round(hi, 4)])

        final_k = sum(1 for r in rows if r.get("correct"))
        lo, hi = wilson(final_k, len(rows))
        out.append({
            "key": spec["key"],
            "label": spec["label"],
            "note": spec["note"],
            "n": len(rows),
            "p": round(final_k / len(rows), 4),
            "lo": round(lo, 4),
            "hi": round(hi, 4),
            "pts": pts,
        })

    body = ",\n".join(
        "  {\n"
        f"    key: {json.dumps(r['key'])},\n"
        f"    label: {json.dumps(r['label'])},\n"
        f"    note: {json.dumps(r['note'])},\n"
        f"    n: {r['n']}, p: {r['p']}, lo: {r['lo']}, hi: {r['hi']},\n"
        f"    pts: {json.dumps(r['pts'], separators=(',', ':'))},\n"
        "  }"
        for r in out
    )

    with open(OUT, "w") as fh:
        fh.write(
            "/**\n"
            " * GENERATED by probe/build_convergence.py. Do not edit.\n"
            " *\n"
            " * One entry per repeated-sampling run. `pts` is\n"
            " * [generations, running rate, 95% low, 95% high], Wilson interval,\n"
            " * dense to the first %d generations then thinned to every %dth.\n"
            " */\n"
            "export type ConvPoint = readonly [number, number, number, number];\n"
            "export type ConvRun = {\n"
            "  readonly key: string;\n"
            "  readonly label: string;\n"
            "  readonly note: string;\n"
            "  readonly n: number;\n"
            "  readonly p: number;\n"
            "  readonly lo: number;\n"
            "  readonly hi: number;\n"
            "  readonly pts: readonly ConvPoint[];\n"
            "};\n\n"
            "export const CONVERGENCE: readonly ConvRun[] = [\n{body},\n];\n"
            .replace("%d generations then thinned to every %dth", 
                     f"{DENSE_TO} generations then thinned to every {THIN}th")
            .replace("{body}", body)
        )

    print(f"wrote {OUT}")
    for r in out:
        print(f"  {r['label']:<8} {r['note']:<14} n={r['n']:>5}  "
              f"{r['p']:.1%}  [{r['lo']:.1%}, {r['hi']:.1%}]  {len(r['pts'])} points")


if __name__ == "__main__":
    main()
