#!/usr/bin/env python3
"""Paired Qwen/Phi cells -> blog/src/lib/data/winner.ts

    python probe/build_winner.py

Ports the published winner surface into the blog. Emits per-cell rates plus the
three findings the figure's caption states, because a caption that hardcodes a
number keeps quoting it after the data stops supporting it -- which is exactly
what happened when the estimator changed from "ever solved" to P(correct) and
four charts kept printing the old figures.

Every number the component or its prose can show is computed here, from
probe/paired.py, the same loader the published charts use.
"""
import argparse
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paired  # noqa: E402

OUT = "blog/src/lib/data/winner.ts"

HEADER = '''/**
 * GENERATED by probe/build_winner.py -- do not edit.
 *
 * One entry per grid cell: how many problems stand behind it, and each model's
 * probability of returning the exactly correct product. A cell is the mean over
 * its problems of that problem's success rate, so every problem counts once no
 * matter how often it was re-run.
 *
 * `findings` holds the numbers the caption states. They are computed alongside
 * the cells rather than written into the prose, because a hardcoded caption
 * outlives the data that justified it.
 */
export type WinnerCell = {
  /** problems behind this cell: 3, 6 or 12 */
  readonly n: number;
  readonly qwen: number;
  readonly phi: number;
};

export type WinnerData = {
  readonly dim: number;
  readonly models: readonly [string, string];
  readonly problems: number;
  /** raw generations per model, unequal, which is why "ever solved" is not used */
  readonly generations: readonly [number, number];
  readonly overall: readonly [number, number];
  readonly cells: Readonly<Record<string, WinnerCell>>;
  /** [B0, B1, B2] per model, for logit(p) = B0 + B1*(a+b) + B2*min(a,b).
   *  Setting the logit to zero solves each model's 50% boundary in closed
   *  form: two straight rays meeting on the diagonal at `halfAt`. Exported so
   *  the boundary figure draws the fit that produced `halfAt` rather than a
   *  second fit of its own that could drift away from it. */
  readonly fits: readonly [readonly number[], readonly number[]];
  readonly findings: {
    /** cells where Phi's rate is strictly higher */
    readonly phiAhead: number;
    /** cells where Qwen is level or higher */
    readonly qwenLevelOrAhead: number;
    readonly level: number;
    /** of the level ones, how many are both models at 100% */
    readonly levelSaturated: number;
    /** square problem size where each model's fitted rate crosses a half */
    readonly halfAt: readonly [number, number];
    /** cells whose gap exceeds 1.96 SD of two independent binomial draws */
    readonly outsideNoise: number;
    /** how many of those favour Phi */
    readonly outsideNoisePhi: number;
    /** points the rate moves when problem SHAPE changes at a fixed a+b */
    readonly swingWithinTotal: number;
    /** points it moves between totals */
    readonly swingBetweenTotals: number;
  };
};

export const WINNER: WinnerData = '''


def diag(beta):
    """Square problem size where a fit crosses 50%: solve B0 + 2dB1 + dB2 = 0."""
    return -beta[0] / (2 * beta[1] + beta[2])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("-o", "--out", default=OUT)
    args = ap.parse_args()

    inst, gen = paired.load(args.runs)
    g = paired.cells(inst)

    fits = [paired.logistic_fit([(c[0], c[1], v[i] * v[2], v[2])
                                 for c, v in g.items()]) for i in (0, 1)]

    # A cell is outside its noise floor when the two rates differ by more than
    # 1.96 SD of two INDEPENDENT binomial draws. The design is paired, so the
    # true spread is narrower and this bound is generous -- the right direction,
    # since a cell that clears it clears an assumption already helping it.
    out = [(c, v[1] - v[0]) for c, v in g.items()
           if abs(v[1] - v[0]) > 1.96 * math.sqrt(
               max(2 * ((v[0] + v[1]) / 2) * (1 - (v[0] + v[1]) / 2) / v[2], 1e-9))]

    # Shape against total. Both swings must come from the same totals: a total
    # with one chain length has no within-swing to give, and letting it into the
    # between-swing compares a range over one set against a range over a wider.
    tot = {}
    for (a, b), (q, p, n) in g.items():
        tot.setdefault(a + b, {}).setdefault(min(a, b), []).append((q, n))
    swings, means = [], []
    for t, d in tot.items():
        if len(d) < 2:
            continue
        rs = [sum(x[0] * x[1] for x in v) / sum(x[1] for x in v) for v in d.values()]
        swings.append(max(rs) - min(rs))
        w = [x for v in d.values() for x in v]
        means.append(sum(x[0] * x[1] for x in w) / sum(x[1] for x in w))

    data = {
        "dim": max(max(c) for c in g),
        "models": [paired.QWEN, paired.PHI],
        "problems": len(inst),
        "generations": [gen[1], gen[3]],
        "overall": [round(gen[0] / gen[1], 4), round(gen[2] / gen[3], 4)],
        "cells": {f"{a}x{b}": {"n": n, "qwen": round(q, 4), "phi": round(p, 4)}
                  for (a, b), (q, p, n) in sorted(g.items())},
        "fits": [[round(x, 6) for x in f] for f in fits],
        "findings": {
            "phiAhead": sum(1 for q, p, n in g.values() if p > q),
            "qwenLevelOrAhead": sum(1 for q, p, n in g.values() if q >= p),
            "level": sum(1 for q, p, n in g.values() if q == p),
            "levelSaturated": sum(1 for q, p, n in g.values() if q == p == 1.0),
            "halfAt": [round(diag(fits[0]), 2), round(diag(fits[1]), 2)],
            "outsideNoise": len(out),
            "outsideNoisePhi": sum(1 for _, d in out if d > 0),
            "swingWithinTotal": round(sum(swings) / len(swings), 4),
            "swingBetweenTotals": round(max(means) - min(means), 4),
        },
    }

    body = json.dumps(data, indent=1)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = args.out if os.path.isabs(args.out) else os.path.join(root, args.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(HEADER + body + ";\n")

    f = data["findings"]
    print(f"wrote {args.out}  ({os.path.getsize(path)/1024:.0f} KB)")
    print(f"  {data['problems']} problems, {len(g)} cells, "
          f"Qwen {data['overall'][0]*100:.1f}% Phi {data['overall'][1]*100:.1f}%")
    print(f"  Phi ahead in {f['phiAhead']}, Qwen level or ahead in "
          f"{f['qwenLevelOrAhead']}  ({f['phiAhead']+f['qwenLevelOrAhead']} = {len(g)})")
    print(f"  50% at {f['halfAt'][0]}^2 and {f['halfAt'][1]}^2")
    print(f"  {f['outsideNoise']} cells outside the noise floor, "
          f"{f['outsideNoisePhi']} favouring Phi")
    print(f"  swing within {f['swingWithinTotal']*100:.1f} pts, "
          f"between {f['swingBetweenTotals']*100:.1f} pts")


if __name__ == "__main__":
    main()
