/**
 * GENERATED by scripts/build-figure-stills.mjs -- do not edit by hand.
 *
 * What each figure looks like, for a reader with JavaScript off. Animated
 * where the figure animates. Only ever fetched by that reader: markup inside
 * <noscript> is not parsed when scripting is on, so nobody else pays for it.
 */
export const FIGURE_STILLS: Record<string, string> = {
  'rings': 'rings.gif',
  'dogfight': 'dogfight.gif',
  'thinking-mix': 'thinking-mix.png',
  'grid-key': 'grid-key.png',
  'synced-trace': 'synced-trace.gif',
  'allocation': 'allocation.png',
  'surface': 'surface.gif',
  'distribution': 'distribution.gif',
  'boundary': 'boundary.png',
};
