/**
 * GENERATED by probe/build_sampling.py. Do not edit.
 *
 * OBSERVED COUNTS ONLY. Nothing in this file is simulated.
 * Pool: Qwen/Qwen3-4B at temperature 0.7, reasoning on, full token allowance.
 *
 * PAIRS      a x b against b x a. Same difficulty under N = a*b.
 * REMEASURED one cell scored in several separate sweeps.
 * REPEATS    one problem run five times, at 4x4, temperature 1.0.
 */
export const POOL_LABEL = "Qwen3-4B, temperature 0.7, 2,634 generations";

export type Pair = {
  readonly n: number; readonly a: number; readonly b: number;
  readonly hitsAB: number; readonly ofAB: number;
  readonly hitsBA: number; readonly ofBA: number;
};
export const PAIRS: readonly Pair[] = [{"n": 39, "a": 3, "b": 13, "hitsAB": 18, "ofAB": 25, "hitsBA": 20, "ofBA": 25}, {"n": 42, "a": 3, "b": 14, "hitsAB": 14, "ofAB": 25, "hitsBA": 12, "ofBA": 25}, {"n": 48, "a": 4, "b": 12, "hitsAB": 26, "ofAB": 30, "hitsBA": 21, "ofBA": 28}, {"n": 55, "a": 5, "b": 11, "hitsAB": 16, "ofAB": 20, "hitsBA": 14, "ofBA": 21}, {"n": 56, "a": 4, "b": 14, "hitsAB": 14, "ofAB": 25, "hitsBA": 15, "ofBA": 25}, {"n": 65, "a": 5, "b": 13, "hitsAB": 13, "ofAB": 25, "hitsBA": 14, "ofBA": 25}, {"n": 70, "a": 5, "b": 14, "hitsAB": 15, "ofAB": 25, "hitsBA": 5, "ofBA": 25}, {"n": 88, "a": 8, "b": 11, "hitsAB": 9, "ofAB": 22, "hitsBA": 134, "ofBA": 277}];

export type Score = { readonly hits: number; readonly of: number };
export type Remeasured = {
  readonly a: number; readonly b: number;
  readonly scores: readonly Score[]; readonly spread: number;
};
export const REMEASURED: readonly Remeasured[] = [{"a": 11, "b": 8, "scores": [{"hits": 2, "of": 6}, {"hits": 123, "of": 256}, {"hits": 6, "of": 12}], "spread": 0.16666666666666669}];

export const REPEAT_LABEL = "4x4, 20 problems, 5 runs each";
export const REPEATS: readonly Score[] = [{"hits": 0, "of": 5}, {"hits": 2, "of": 5}, {"hits": 2, "of": 5}, {"hits": 2, "of": 5}, {"hits": 2, "of": 5}, {"hits": 3, "of": 5}, {"hits": 3, "of": 5}, {"hits": 3, "of": 5}, {"hits": 3, "of": 5}, {"hits": 3, "of": 5}, {"hits": 3, "of": 5}, {"hits": 4, "of": 5}, {"hits": 4, "of": 5}, {"hits": 4, "of": 5}, {"hits": 4, "of": 5}, {"hits": 4, "of": 5}, {"hits": 5, "of": 5}, {"hits": 5, "of": 5}, {"hits": 5, "of": 5}, {"hits": 5, "of": 5}];

/** Resampled from one cell's OBSERVED outcomes, with replacement.
 *  counts[k] = how many draws of `size` came back with k correct. */
export type Bootstrap = { readonly size: number; readonly counts: readonly number[] };
/** OBSERVED. counts[k] = how many independent groups of `group`
 *  came back with k correct. No resampling. */
export const SCORES_LABEL = "5x5 reasoning off, 6,000 generations in 500 groups of 12";
export const SCORES_GROUP = 12;
export const SCORES_RATE = 0.57717;
export const SCORES: readonly number[] = [0, 2, 2, 10, 28, 71, 95, 102, 89, 56, 35, 10, 0];

export const BOOTSTRAP_LABEL = "11x8, resampled from 134 correct of 277 generations";
export const BOOTSTRAP: readonly Bootstrap[] = [{"size": 3, "counts": [2802, 7659, 7232, 2307]}, {"size": 6, "counts": [394, 2209, 4771, 6193, 4469, 1705, 259]}, {"size": 12, "counts": [7, 80, 402, 1284, 2710, 4138, 4450, 3582, 2151, 879, 266, 47, 4]}];
