/**
 * GENERATED by probe/build_thinking_mix.py -- do not edit.
 *
 * Per-model share of labelled thinking segments, from the PUBLISHED labels in
 * agent-capability-threshold. The data is not copied into this repo; `source`
 * below carries the commit and the URL so any number here can be traced to the
 * bytes it came from.
 *
 * CATEGORIES, NOT OODA PHASES. The v1 rubric maps `STRATEGY` (this scheme's
 * `DECOMPOSITION`) to both Orient and Decide, so a phase chart would have to
 * double-count the largest category. See the build script for the full
 * argument.
 */
export type MixModel = {
  readonly model: string;
  readonly traces: number;
  readonly segments: number;
  /** category -> segment count */
  readonly counts: Readonly<Record<string, number>>;
};

export type ThinkingMix = {
  readonly order: readonly string[];
  readonly labels: Readonly<Record<string, string>>;
  readonly models: readonly MixModel[];
  readonly segments: number;
  readonly source: {
    readonly repo: string;
    readonly path: string;
    readonly commit: string;
    readonly url: string;
  };
};

export const THINKING_MIX: ThinkingMix = {
 "order": [
  "TASK_SETUP",
  "DECOMPOSITION",
  "PROCEDURAL_TRACKING",
  "ARITHMETIC",
  "EXECUTION",
  "VERIFICATION",
  "ERROR_CORRECTION",
  "SURRENDER_DELIBERATION"
 ],
 "labels": {
  "TASK_SETUP": "Setup",
  "DECOMPOSITION": "Decomposition",
  "PROCEDURAL_TRACKING": "State tracking",
  "ARITHMETIC": "Arithmetic",
  "EXECUTION": "Connective",
  "VERIFICATION": "Verification",
  "ERROR_CORRECTION": "Error correction",
  "SURRENDER_DELIBERATION": "Deciding to quit"
 },
 "models": [
  {
   "model": "haiku",
   "traces": 2,
   "segments": 373,
   "counts": {
    "TASK_SETUP": 13,
    "DECOMPOSITION": 14,
    "PROCEDURAL_TRACKING": 125,
    "ARITHMETIC": 144,
    "EXECUTION": 30,
    "VERIFICATION": 28,
    "ERROR_CORRECTION": 16,
    "SURRENDER_DELIBERATION": 3
   }
  },
  {
   "model": "opus",
   "traces": 4,
   "segments": 312,
   "counts": {
    "TASK_SETUP": 20,
    "DECOMPOSITION": 41,
    "PROCEDURAL_TRACKING": 57,
    "ARITHMETIC": 81,
    "EXECUTION": 27,
    "VERIFICATION": 52,
    "ERROR_CORRECTION": 19,
    "SURRENDER_DELIBERATION": 15
   }
  },
  {
   "model": "sonnet",
   "traces": 2,
   "segments": 218,
   "counts": {
    "TASK_SETUP": 18,
    "DECOMPOSITION": 68,
    "PROCEDURAL_TRACKING": 43,
    "ARITHMETIC": 34,
    "EXECUTION": 5,
    "VERIFICATION": 37,
    "ERROR_CORRECTION": 5,
    "SURRENDER_DELIBERATION": 8
   }
  }
 ],
 "segments": 903,
 "source": {
  "repo": "https://github.com/adam-s/agent-capability-threshold",
  "path": "web/src/lib/data/annotated-traces.ts",
  "commit": "550531cf9452c18af4097e2993a84c1b0c2c731e",
  "url": "https://github.com/adam-s/agent-capability-threshold/blob/550531cf9452c18af4097e2993a84c1b0c2c731e/web/src/lib/data/annotated-traces.ts"
 }
};
