/**
 * GENERATED by probe/build_winner.py -- do not edit.
 *
 * One entry per grid cell: how many problems stand behind it, and each model's
 * probability of returning the exactly correct product. A cell is the mean over
 * its problems of that problem's success rate, so every problem counts once no
 * matter how often it was re-run.
 *
 * `findings` holds the numbers the caption states. They are computed alongside
 * the cells rather than written into the prose, because a hardcoded caption
 * outlives the data that justified it.
 */
export type WinnerCell = {
  /** problems behind this cell: 3, 6 or 12 */
  readonly n: number;
  readonly qwen: number;
  readonly phi: number;
};

export type WinnerData = {
  readonly dim: number;
  readonly models: readonly [string, string];
  readonly problems: number;
  /** raw generations per model, unequal, which is why "ever solved" is not used */
  readonly generations: readonly [number, number];
  readonly overall: readonly [number, number];
  readonly cells: Readonly<Record<string, WinnerCell>>;
  readonly findings: {
    /** cells where Phi's rate is strictly higher */
    readonly phiAhead: number;
    /** cells where Qwen is level or higher */
    readonly qwenLevelOrAhead: number;
    readonly level: number;
    /** of the level ones, how many are both models at 100% */
    readonly levelSaturated: number;
    /** square problem size where each model's fitted rate crosses a half */
    readonly halfAt: readonly [number, number];
    /** cells whose gap exceeds 1.96 SD of two independent binomial draws */
    readonly outsideNoise: number;
    /** how many of those favour Phi */
    readonly outsideNoisePhi: number;
    /** points the rate moves when problem SHAPE changes at a fixed a+b */
    readonly swingWithinTotal: number;
    /** points it moves between totals */
    readonly swingBetweenTotals: number;
  };
};

export const WINNER: WinnerData = {
 "dim": 12,
 "models": [
  "Qwen3-4B",
  "Phi-4-reasoning"
 ],
 "problems": 1062,
 "generations": [
  1579,
  1206
 ],
 "overall": [
  0.7441,
  0.5978
 ],
 "cells": {
  "1x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x4": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x5": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x6": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x7": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x8": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x9": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.8333
  },
  "1x10": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x11": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "1x12": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x4": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x5": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x6": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x7": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x8": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.8333
  },
  "2x9": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "2x10": {
   "n": 3,
   "qwen": 0.6667,
   "phi": 1.0
  },
  "2x11": {
   "n": 3,
   "qwen": 0.8333,
   "phi": 0.5
  },
  "2x12": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 0.8333
  },
  "3x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x4": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x5": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x6": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x7": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x8": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "3x9": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.5833
  },
  "3x10": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 1.0
  },
  "3x11": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "3x12": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 1.0
  },
  "4x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "4x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "4x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "4x4": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "4x5": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "4x6": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "4x7": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.8333
  },
  "4x8": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "4x9": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.5833
  },
  "4x10": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.0833
  },
  "4x11": {
   "n": 12,
   "qwen": 0.9167,
   "phi": 0.75
  },
  "4x12": {
   "n": 12,
   "qwen": 0.8889,
   "phi": 0.625
  },
  "5x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "5x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "5x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "5x4": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "5x5": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "5x6": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 1.0
  },
  "5x7": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "5x8": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.75
  },
  "5x9": {
   "n": 12,
   "qwen": 1.0,
   "phi": 0.75
  },
  "5x10": {
   "n": 12,
   "qwen": 0.875,
   "phi": 0.8333
  },
  "5x11": {
   "n": 12,
   "qwen": 0.7917,
   "phi": 0.625
  },
  "5x12": {
   "n": 12,
   "qwen": 0.7917,
   "phi": 0.4167
  },
  "6x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "6x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "6x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "6x4": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "6x5": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.8333
  },
  "6x6": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "6x7": {
   "n": 12,
   "qwen": 0.9583,
   "phi": 0.9167
  },
  "6x8": {
   "n": 12,
   "qwen": 0.9167,
   "phi": 0.5417
  },
  "6x9": {
   "n": 12,
   "qwen": 0.9583,
   "phi": 0.75
  },
  "6x10": {
   "n": 12,
   "qwen": 0.875,
   "phi": 0.5
  },
  "6x11": {
   "n": 12,
   "qwen": 0.625,
   "phi": 0.5
  },
  "6x12": {
   "n": 12,
   "qwen": 0.5,
   "phi": 0.3333
  },
  "7x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "7x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "7x3": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "7x4": {
   "n": 6,
   "qwen": 1.0,
   "phi": 1.0
  },
  "7x5": {
   "n": 6,
   "qwen": 0.9444,
   "phi": 0.8333
  },
  "7x6": {
   "n": 12,
   "qwen": 0.7917,
   "phi": 0.75
  },
  "7x7": {
   "n": 12,
   "qwen": 0.7917,
   "phi": 0.6667
  },
  "7x8": {
   "n": 12,
   "qwen": 0.8333,
   "phi": 0.625
  },
  "7x9": {
   "n": 12,
   "qwen": 0.6389,
   "phi": 0.625
  },
  "7x10": {
   "n": 12,
   "qwen": 0.75,
   "phi": 0.125
  },
  "7x11": {
   "n": 12,
   "qwen": 0.4167,
   "phi": 0.4167
  },
  "7x12": {
   "n": 12,
   "qwen": 0.4583,
   "phi": 0.6667
  },
  "8x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "8x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "8x3": {
   "n": 6,
   "qwen": 0.9167,
   "phi": 0.6667
  },
  "8x4": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.8333
  },
  "8x5": {
   "n": 6,
   "qwen": 0.9167,
   "phi": 1.0
  },
  "8x6": {
   "n": 12,
   "qwen": 1.0,
   "phi": 0.7083
  },
  "8x7": {
   "n": 12,
   "qwen": 0.7083,
   "phi": 0.5417
  },
  "8x8": {
   "n": 12,
   "qwen": 0.8333,
   "phi": 0.8333
  },
  "8x9": {
   "n": 12,
   "qwen": 0.7083,
   "phi": 0.5833
  },
  "8x10": {
   "n": 12,
   "qwen": 0.4583,
   "phi": 0.6667
  },
  "8x11": {
   "n": 12,
   "qwen": 0.5069,
   "phi": 0.1667
  },
  "8x12": {
   "n": 12,
   "qwen": 0.3194,
   "phi": 0.25
  },
  "9x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "9x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "9x3": {
   "n": 6,
   "qwen": 1.0,
   "phi": 0.8333
  },
  "9x4": {
   "n": 6,
   "qwen": 0.9167,
   "phi": 1.0
  },
  "9x5": {
   "n": 12,
   "qwen": 0.875,
   "phi": 0.5
  },
  "9x6": {
   "n": 12,
   "qwen": 0.9306,
   "phi": 0.8333
  },
  "9x7": {
   "n": 12,
   "qwen": 0.875,
   "phi": 0.6667
  },
  "9x8": {
   "n": 12,
   "qwen": 0.5833,
   "phi": 0.5
  },
  "9x9": {
   "n": 12,
   "qwen": 0.5417,
   "phi": 0.5833
  },
  "9x10": {
   "n": 12,
   "qwen": 0.4167,
   "phi": 0.5833
  },
  "9x11": {
   "n": 12,
   "qwen": 0.3333,
   "phi": 0.2083
  },
  "9x12": {
   "n": 12,
   "qwen": 0.2917,
   "phi": 0.0833
  },
  "10x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "10x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "10x3": {
   "n": 6,
   "qwen": 0.75,
   "phi": 1.0
  },
  "10x4": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 0.8333
  },
  "10x5": {
   "n": 12,
   "qwen": 0.75,
   "phi": 0.5833
  },
  "10x6": {
   "n": 12,
   "qwen": 0.8333,
   "phi": 0.4167
  },
  "10x7": {
   "n": 12,
   "qwen": 0.6667,
   "phi": 0.2083
  },
  "10x8": {
   "n": 12,
   "qwen": 0.5417,
   "phi": 0.2917
  },
  "10x9": {
   "n": 12,
   "qwen": 0.5417,
   "phi": 0.4583
  },
  "10x10": {
   "n": 12,
   "qwen": 0.4583,
   "phi": 0.1667
  },
  "10x11": {
   "n": 12,
   "qwen": 0.1944,
   "phi": 0.0833
  },
  "10x12": {
   "n": 12,
   "qwen": 0.125,
   "phi": 0.0833
  },
  "11x1": {
   "n": 3,
   "qwen": 1.0,
   "phi": 0.6667
  },
  "11x2": {
   "n": 3,
   "qwen": 1.0,
   "phi": 1.0
  },
  "11x3": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 0.6667
  },
  "11x4": {
   "n": 12,
   "qwen": 0.8194,
   "phi": 0.75
  },
  "11x5": {
   "n": 12,
   "qwen": 0.75,
   "phi": 0.4583
  },
  "11x6": {
   "n": 12,
   "qwen": 0.625,
   "phi": 0.25
  },
  "11x7": {
   "n": 12,
   "qwen": 0.75,
   "phi": 0.2917
  },
  "11x8": {
   "n": 12,
   "qwen": 0.5972,
   "phi": 0.3333
  },
  "11x9": {
   "n": 12,
   "qwen": 0.3333,
   "phi": 0.125
  },
  "11x10": {
   "n": 12,
   "qwen": 0.0,
   "phi": 0.0833
  },
  "11x11": {
   "n": 12,
   "qwen": 0.1389,
   "phi": 0.0
  },
  "11x12": {
   "n": 12,
   "qwen": 0.1667,
   "phi": 0.0
  },
  "12x1": {
   "n": 3,
   "qwen": 0.8333,
   "phi": 1.0
  },
  "12x2": {
   "n": 6,
   "qwen": 0.8333,
   "phi": 0.4167
  },
  "12x3": {
   "n": 6,
   "qwen": 0.9444,
   "phi": 0.8333
  },
  "12x4": {
   "n": 12,
   "qwen": 0.7222,
   "phi": 0.75
  },
  "12x5": {
   "n": 12,
   "qwen": 0.625,
   "phi": 0.4167
  },
  "12x6": {
   "n": 12,
   "qwen": 0.875,
   "phi": 0.3333
  },
  "12x7": {
   "n": 12,
   "qwen": 0.25,
   "phi": 0.2083
  },
  "12x8": {
   "n": 12,
   "qwen": 0.25,
   "phi": 0.0833
  },
  "12x9": {
   "n": 12,
   "qwen": 0.375,
   "phi": 0.2083
  },
  "12x10": {
   "n": 12,
   "qwen": 0.0833,
   "phi": 0.0
  },
  "12x11": {
   "n": 12,
   "qwen": 0.0417,
   "phi": 0.0833
  },
  "12x12": {
   "n": 12,
   "qwen": 0.125,
   "phi": 0.0833
  }
 },
 "findings": {
  "phiAhead": 15,
  "qwenLevelOrAhead": 129,
  "level": 55,
  "levelSaturated": 51,
  "halfAt": [
   9.24,
   8.39
  ],
  "outsideNoise": 10,
  "outsideNoisePhi": 0,
  "swingWithinTotal": 0.093,
  "swingBetweenTotals": 0.8843
 }
};
